### PR TITLE
Modernize the codebase

### PR DESCRIPTION
**Pull request by Ashish-Bansal**
Includes work from @Kompwu and @sheldonled!

~It's not ready to be merged yet. I still need to fix lot of things in this rewrite.~

Thanks!

Update: @Kompwu will work on porting it to Fusebox and then I'll continue with refactoring.

### CODE REVIEW

**Comment by Kompwu** [comment]
@Ashish-Bansal Webpack is bad.
We should use FuseBox or Parcel to bundle everything.
Also, consider TypeScript !
I can make a PR to migrate to TypeScript if you want.
I can also make one for Parcel/FuseBox.

**Comment by Ashish-Bansal** [comment]
@Kompwu I'm not aware of FuseBox or Parcel. I just checked out FuseBox and seems like it's easy to configure at first look. If you are interested, then sure, feel free to port it from webpack to fusebox. Though please make sure all the features used in webpack are retained in it. 

And I again won't be able to work on it till next weekend. 

Thanks!

**Comment by Ashish-Bansal** [comment]
I'm merging it to master since I didn't encounter any bugs in this refactor.

**Comment by Kompwu** [comment]
@Ashish-Bansal Sure, I'm gonna work on it today :wink: 
Edit: Not yet finished, I'm gonna continue tomorrow.

**Pull request merged**
