### PR TITLE
Modernize the codebase [WIP]

### PR DESCRIPTION
**Pull request by Kompwu**
The code is really old, and hard to maintain.
I started rewriting this whole mess, but I need help!

- [x] start refactor `background` in a class.

### CODE REVIEW

**Comment by Kompwu** [comment]
Ping @sheldonled i think you can help :)

**Comment by craftwar** [comment]
I have rewritten a few month ago. code size reduces to about 1/2.
FYR https://github.com/craftwar/youtube-audio

**Comment by Kompwu** [comment]
@craftwar Your version's also a mess...
anyway, can you help ?
Maybe we should work on your / @sheldonled base.

**Comment by craftwar** [comment]
@Kompwu I don't know what you mean
That is my first firefox extension, I learn js when rewriting it.
I don't know many js features.

My base is not this repo, you can read #22

**Comment by Ashish-Bansal** [comment]
@Kompwu Thanks a lot for taking a step forward! I'll work on it this weekend.

**Comment by Kompwu** [comment]
@craftwar I was talking about your fork :)
@Ashish-Bansal Okay, lemme know.

**Comment by Ashish-Bansal** [comment]
@Kompwu I have merged your work in #36. So, I'm closing this up.

**Pull request closed without merging**
